#!/bin/bash

# while-menu: a menu-driven system information program

DELAY=15 # Number of seconds to display results
TIME=3   # 

while true; do
  clear
  cat << _EOF_

1. vim
2. tmux
3. mutt
4. fzf
5. ranger
6. date
7. dwm
0. quit

_EOF_

  read -p "Enter selection [0-7] > "

  if [[ $REPLY =~ ^[0-7]$ ]]; then
    case $REPLY in
      1)
        cat ~/Documents/raccourcis/raccourcisVim
        sleep $DELAY
        continue
        ;;
      2)
        cat ~/Documents/raccourcis/raccourcisTmux
        sleep $DELAY
        continue
        ;;
      3)
				cat ~/Documents/raccourcis/raccourcisMutt
        sleep $DELAY
        continue
        ;;
			4)
				cat ~/Documents/raccourcis/raccourcisFzf
				sleep $DELAY
				continue
				;;
			5)
				cat ~/Documents/raccourcis/raccourcisRanger
				sleep $DELAY
				continue
				;;
			6)
				cat ~/Documents/raccourcis/timeFormat
				sleep $DELAY
				continue
				;;
			7)
				cat ~/Documents/raccourcis/dwm
				sleep $DELAY
				continue
				;;
      0)
        break
        ;;
    esac
  else
    echo "Invalid entry."
    sleep $TIME
  fi
done
echo "A +"
