#!/bin/bash

DISPLAY=:0
# DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus setpriv --euid=1000 notify-send -i /usr/share/icons/Adwaita/16x16/mimetypes/x-office-calendar-symbolic.symbolic.png -t 0 "Calendrier" "$(/home/gilles/scripts/rem_color)"
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus setpriv --euid=1000 notify-send "$(mocp -Q "%a - %t (%A)")"
