#!/bin/bash

# Remind popup notification
# IMPORTANT : chmod +x notifremindtoday
# need dunst
# use crontab -e to schedule script execution
# add the following line
# 0 * * * * env DISPLAY=:0.O /home/gilles/scripts/notifremindtoday
# le script s'exécutera toutes les heures (01h00, 02h00, ...)

# les rdv du jour (rem)
# myremind="$(rem)"

# les rdv pour les 2 semaines à venir
myremind="$(rem -s2 |awk '{print $1, $6, $7}')"
# echo "$myremind"

madate="$(date +"%Y/%m/%d")"
# echo $madate

remindoftoday="$(rem -s2 |awk -v ref="$madate" 'match($0, ref) {print $0}' |cut -d ' ' -f1,6-)"
# echo "$remindoftoday"

export DISPLAY=:0.0

# test
if [[ $remindoftoday == "" ]]; then
	exit 0
else
 notify-send -u critical "Rappel" "<span color='#57dafd'>${remindoftoday}</span>" >/dev/null 2>&1
fi
