#!/bin/env sh
# rsj : radio swiss jazz
# https://www.radioswissjazz.ch/fr
# http://stream.srg-ssr.ch/m/rsj/mp3_128

command -v mocp >/dev/null 2>&1 || exit
! pgrep -x mocp >/dev/null && mocp -S
mocp -c
mocp -a "http://stream.srg-ssr.ch/m/rsj/mp3_128"
mocp -p
