#!/bin/sh
# -r, --recursive recurse into directories
# -l, --links copy symlinks as symlinks
# -t, --times preserve modification times
# -z, --compress compress file data during the transfer
# -u, --update skip files that are newer on the receiver

command -v rsync >/dev/null 2>&1 || exit

if ! grep -qs '/media/usb1 ' /proc/mounts;then
	echo "La clé n'est pas montée" && exit
else
# 	rsync -rltzuv --delete \
# 	--exclude=vim/.vim/ \
# 	--exclude=surf \
# 	--exclude=config/.config/libreoffice/ \
# 	--exclude=config/.config/pulse/ \
# 		/home/gilles/dotfiles/ /media/usb1/dotfiles/
	rsync -rltzuv --delete ~/.abook/addressbook /media/usb1/contacts/
	rsync -rltzuv --delete ~/reminds/ /media/usb1/reminds/
	rsync -rltzuv --delete ~/scripts/ /media/usb1/scripts/
fi
